### ISSUE TITLE
ImportError due to lxml.html.clean

### ISSUE THREAD

**Issue by teddythepooh** [urban-labs/namematch#20]
Bhavya's NM env is based off the .yml file below. While going through `./examples/end_to_end_tutorial.ipynb`, she encountered two issues in importing `namematch`. I was also able to reproduce them on my end:

1. Warning: `Your CPU supports instructions that this binary was not compiled to use: SSE3. For maximum performance, you can install NMSLIB from sources pip install --no-binary :all: nmslib`
2. ImportError: `lxml.html.clean module is now a separate project lxml_html_clean. Install lxml[html_clean] or lxml_html_clean directly.`

```yaml
name: my_nm_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.20
  - pip=24.3.1
  - pip:
      - namematch==1.2.1
```

I instructed her to update her environment through `pip install --no-binary :all: nmslib` and `pip install lxml_html_clean`, which resolved the aforementioned issues. I never encountered these issues before, presumably because I used an older version of NM in the past.
